# 模块一：函数式编程与JS异步编程、手写Promise

## 一、谈谈你是如何理解JS异步编程的，EventLoop、消息队列都是做什么的，什么是宏任务，什么是微任务？

A: 
- 1. 对异步编程的理解：JS语言执行环境是单线程的，这种模式执行效率较低，任务耗时长；任务复杂时容易造成阻塞。所以就需要异步模式，异步模式使得JS在处理事务时非常高效，但同时也带来了异常处理困难、嵌套过深等副作用。

- 2. EventLoop、消息队列作用：在JS中，所有同步任务都在主线程上执行，即执行栈。

    主线程外，还有一个任务队列，任务队列的作用是等待异步任务的结果，只要异步任务有了运行结果，就会加入到消息队列中，一旦执行栈中所有同步任务执行完毕，就从消息队列中读取加入到执行栈中。
    消息队列特点是先进先出

- 3. 宏任务：宏任务是参与了事件循环的异步任务，例如setTimeout、setInterval

- 4. 微任务： 微任务是没有参与事件循环的异步任务，例如Promise

## 二、将下面异步代码使用promise的方式改进
```javascript
let promise = new Promise((resolve, reject) => {
    setTimeout(() => {
        var a = 'hello '
        resolve(a)
    }, 10)
})
setTimeout(() => {
    promise.then(val => {
        var b = 'lagou '
        return val + b
    }).then(val => {
        setTimeout(() => {
            var c = 'I ♥ U'
            console.log(val + c)
        }, 10)
    })
}, 20)
```

## 三、基于以下代码完成下面四个练习

### 3-1
```javascript
const fp = require("lodash/fp")
let fr = fp.flowRight(fp.prop('in_stock'),fp.last)
console.log(fr(cars))
```

### 3-2
```javascript
const fp = require("lodash/fp")
let fr = fp.flowRight(fp.prop('name'), fp.first)
console.log(fr(cars))
```

### 3-3
```javascript
const fp = require("lodash/fp")
let _average = function(xs) {
    return fp.reduce(fp.add, 0, xs) / xs.length
}
let averageDollarValue = function(cars) {
    let fr = fp.flowRight(_average, fp.map(car => car.dollar_value))
    return fr(cars)
}
```

### 3-4
```javascript
const fp = require("lodash/fp")
let _underscore = fp.replace(/\W+/g,"_")
function sanitizeNames() {
    return fp.flowRight(fp.map(name => _underscore(name)))
}
```

## 四、基于下面提供的代码，完成后续的四个练习

### 4-1
```javascript
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let maybe = Maybe.of([5, 6, 1])
let ex1 = () => {
    let fr = fp.flowRight(fp.map(fp.add(num)))
    return maybe.map(fr)
}
console.log(ex1(1))
```

### 4-2
```javascript
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let xs = Container.of(['do','ray','me','fa','so','la','ti','do'])
let ex2 = () => {
    return xs.map(fp.first)._value
}
console.log(ex2())
```

### 4-3
```javascript
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let safeProp = fp.curry(function (x, o) {
    return Maybe.of(o[x])
})
let user = { id: 2, name: 'Albert' }
let ex3 = () => {
    return safeProp('name', user).map(fp.first)._value
}
console.log(ex3())
```

### 4-4
```javascript
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let ex4 = function(n) {
    let m1 = new Maybe(n)
    let m2 = m1.map(parseInt)
    return m2._value
}
console.log(ex4(1))
```

## 五、手写实现MyPromise源码
```javascript
const PEDDING = 'pedding' //等待
const FUFILLED = 'fufilled' //成功
const REJECT = 'reject' //失败

class MyPromise {
    constructor(exeuctor) {
        try {
            exeuctor(this.resolve, this.reject)
        } catch (error) {
            this.reject(error)
        }
    }
    // 全局状态
    status = PEDDING
    //成功之后的值
    value = undefined
    //失败之后的原因
    reason = undefined
    //成功的回调
    // successCallback = undefined  只能处理一个回调函数
    successCallback = []
    //失败的回调
    // failCallback = undefined
    failCallback = []


    //使用箭头函数定义是为了执行方法的时候让this指向MyPromise的实例对象
    resolve = value => {
        // 状态不是pendig的时候，不继续执行
        if (this.status !== PEDDING) return
        // 更改状态为成功
        this.status = FUFILLED
        //保存成功之后的值
        this.value = value
        // 异步 成功
        // this.successCallback && this.successCallback(this.value)
        while (this.successCallback.length) {
            // this.successCallback.shift()(this.value)
            this.successCallback.shift()()
        }
    }

    reject = reason => {
        // 状态不是pendig的时候，不继续执行
        if (this.status !== PEDDING) return
        this.status = REJECT
        // 更改状态为失败
        this.reason = reason
        // 异步 失败
        // this.failCallback && this.failCallback(this.reason)
        while (this.failCallback.length) {
            this.failCallback.shift()()
        }
    }

    then(successCallback, errorCallback) {
        // 当then中不传参数时，将原有的状态返回
        successCallback = successCallback ? successCallback : value => value
        errorCallback = errorCallback ? errorCallback : error => { throw error }
        let promise = new MyPromise((resolve, reject) => {
            if (this.status == FULFILLED) {
                setTimeout(() => {
                    try {
                        // 判断val的值是普通值还是Promise对象
                        // 如果是普通值，直接调用resolve
                        // 如果是promise对象，查看promise对象返回的结果
                        // 再根据promise对象返回的结果，决定调用resolve还是调用reject
                        let val = successCallback(this.value)
                        resolvePromise(promise, val, resolve, reject)
                    } catch (e) {
                        reject(e)
                    }
                }, 0)
            } else if (this.status == REJECT) {
                setTimeout(() => {
                    try {
                        // 判断val的值是普通值还是Promise对象
                        // 如果是普通值，直接调用resolve
                        // 如果是promise对象，查看promise对象返回的结果
                        // 再根据promise对象返回的结果，决定调用resolve还是调用reject
                        let val = errorCallback(this.error)
                        resolvePromise(promise, val, resolve, reject)
                    } catch (e) {
                        reject(e)
                    }

                }, 0)
            } else {
                // 当前状态为pending，将两个函数存起来
                this.successCallback.push(() => {
                    // successCallback()
                    try {
                        // 判断val的值是普通值还是Promise对象
                        // 如果是普通值，直接调用resolve
                        // 如果是promise对象，查看promise对象返回的结果
                        // 再根据promise对象返回的结果，决定调用resolve还是调用reject
                        let val = successCallback(this.value)
                        resolvePromise(promise, val, resolve, reject)
                    } catch (e) {
                        reject(e)
                    }
                })
                this.errorCallback.push(() => {
                    // errorCallback()
                    try {
                        // 判断val的值是普通值还是Promise对象
                        // 如果是普通值，直接调用resolve
                        // 如果是promise对象，查看promise对象返回的结果
                        // 再根据promise对象返回的结果，决定调用resolve还是调用reject
                        let val = errorCallback(this.error)
                        resolvePromise(promise, val, resolve, reject)
                    } catch (e) {
                        reject(e)
                    }
                })
            }
        })

        return promise
    }

    finally(callback) {
        return this.then(val => {
            return MyPromise.resolve(callback()).then(() => val)
            // callback()
            // return val
        }, err => {
            return MyPromise.resolve(callback()).then(() => { throw err })
            // callback()
            // throw err
        })
    }

    catch(errorCallback) {
        return this.then(undefined, errorCallback)
    }

    static all(arr) {
        let result = []
        let index = 0

        return new MyPromise((resolve, reject) => {
            function addData(key, val) {
                result[key] = val
                if (index === arr.length) {
                    resolve(result)
                }
            }

            for (let i = 0; i < arr.length; i++) {
                let current = arr[i]
                if (current instanceof MyPromise) {
                    // Promise对象
                    current.then(val => addData(i, val), err => reject(err))
                } else {
                    // 普通值
                    addData(i, arr[i])
                }
            }
        })
    }

    static resolve(value) {
        // 是promise则返回自身
        if (value instanceof MyPromise) return value
        // 不是promise对象则将其转化为promise对象
        return new MyPromise(resolve => resolve(value))
    }

}

function resolvePromise(promise, val, resolve, reject) {
    // 识别自返回，若是则报错
    if (promise === val) {
        return reject(new TypeError("Chaining cycle detected for promise #<Promise>    "))
    }
    if (val instanceof MyPromise) {
        // Promise对象
        val.then(resolve, reject)
    } else {
        // 普通值
        resolve(val)
    }
}

module.exports = MyPromise
```